### ISSUE TITLE
Exception in ShowcaseContent

### ISSUE THREAD

**Issue by realstaticvoid** [canopas/compose-intro-showcase#23]
Hello. I am getting the following exception:

```
 java.lang.IllegalStateException: LayoutCoordinate operations are only valid when isAttached is true
     at androidx.compose.ui.node.NodeCoordinator.getParentLayoutCoordinates(NodeCoordinator.kt:256)
     at androidx.compose.ui.layout.LayoutCoordinatesKt.findRootCoordinates(LayoutCoordinates.kt:180)
     at androidx.compose.ui.layout.LayoutCoordinatesKt.boundsInWindow(LayoutCoordinates.kt:134)
     at com.canopas.lib.showcase.component.ShowcaseContentKt.ShowcaseContent(ShowcaseContent.kt:76)
     at com.canopas.lib.showcase.component.ShowcaseContentKt$ShowcasePopup$1$1.invoke(ShowcaseContent.kt:55)
     at com.canopas.lib.showcase.component.ShowcaseContentKt$ShowcasePopup$1$1.invoke(ShowcaseContent.kt:54)
```
If I debug into the [code](https://github.com/canopas/compose-intro-showcase/blob/master/showcase/src/main/java/com/canopas/lib/showcase/component/ShowcaseContent.kt#L76) I can confirm that the 'targetCords.isAttached' is false and the call of 'targetCords.boundsInWindow()' leads to the exception.

My guess is it has something to do with the fact that I am using a [LazyColum](https://foso.github.io/Jetpack-Compose-Playground/foundation/lazycolumn/). But anyway.. It might be better to handle the 'isAttached == false' case in the library than letting the app crash?

**Comment by vivekgupta4Git** [comment]
By any chance your api level is below 26?

**Comment by realstaticvoid** [comment]
Okey this also happens in other situations for example if I want to target a Composable in a 'trailingIcon' of a [TextField](https://developer.android.com/reference/kotlin/androidx/compose/material/package-summary#TextField(androidx.compose.ui.text.input.TextFieldValue,kotlin.Function1,androidx.compose.ui.Modifier,kotlin.Boolean,kotlin.Boolean,androidx.compose.ui.text.TextStyle,kotlin.Function0,kotlin.Function0,kotlin.Function0,kotlin.Function0,kotlin.Boolean,androidx.compose.ui.text.input.VisualTransformation,androidx.compose.foundation.text.KeyboardOptions,androidx.compose.foundation.text.KeyboardActions,kotlin.Boolean,kotlin.Int,kotlin.Int,androidx.compose.foundation.interaction.MutableInteractionSource,androidx.compose.ui.graphics.Shape,androidx.compose.material.TextFieldColors))

**Comment by Blaizyr** [comment]
1. my sc implementation goes through three different views.
2. the first passthrough is always correct,
3. but at the end of the whole sequence, if I reset the showcase state and jump to the beginning - every transition between already composed views - results in this exception.
In general - every time the showcase increments to the target already composed element on a separate view - the application crashes.

I think instead of trying to consume the coordinates of a composable that was previously drawn, it should force a re-composition or something like that.

**Comment by dmitriy-chernysh** [comment]
Sorry to say but I got a few crashes from users using v2.0.1  

`
Fatal Exception: java.lang.IllegalStateException: LayoutCoordinate operations are only valid when isAttached is true
       at androidx.compose.ui.node.NodeCoordinator.getParentLayoutCoordinates(NodeCoordinator.kt:255)
       at androidx.compose.ui.layout.LayoutCoordinatesKt.findRootCoordinates(LayoutCoordinates.kt:180)
       at androidx.compose.ui.layout.LayoutCoordinatesKt.boundsInWindow(LayoutCoordinates.kt:134)
       at com.canopas.lib.showcase.component.ShowcaseContentKt.ShowcaseContent(ShowcaseContent.kt:76)
       at com.canopas.lib.showcase.component.ShowcaseContentKt$ShowcaseContent$6.invoke(ShowcaseContent.kt:103)
       at com.canopas.lib.showcase.component.ShowcaseContentKt$ShowcaseContent$6.invoke(ShowcaseContent.kt:103)
       at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.java:192)
       at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2556)
       at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2827)
       at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3314)
       at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3265)
       at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:940)
       at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1155)
       at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:127)
       at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:583)
       at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.java:551)
       at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
       at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.java:109)
       at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.java:41)
       at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1648)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1659)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1129)
       at android.view.Choreographer.doFrame(Choreographer.java:1045)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1622)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8900)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
        `

**Comment by RuzickaOnd** [comment]
When will this fix be released, please? Thanks

**Comment by cp-megh-l** [comment]
With v2.0.2, this crash is fixed!

**Comment by imkhalid** [comment]
Still getting this crash on 2.0.2

```
 java.lang.IllegalStateException: LayoutCoordinate operations are only valid when isAttached is true
                                                                                                    	at androidx.compose.ui.internal.InlineClassHelperKt.throwIllegalStateException(InlineClassHelper.kt:28)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.getParentLayoutCoordinates(NodeCoordinator.kt:1801)
                                                                                                    	at androidx.compose.ui.layout.LayoutCoordinatesKt.findRootCoordinates(LayoutCoordinates.kt:253)
                                                                                                    	at androidx.compose.ui.layout.LayoutCoordinatesKt.boundsInWindow(LayoutCoordinates.kt:194)
                                                                                                    	at com.canopas.lib.showcase.component.ShowcaseContentKt.ShowcaseContent(ShowcaseContent.kt:78)
                                                                                                    	at com.canopas.lib.showcase.component.ShowcaseContentKt$ShowcaseContent$6.invoke(Unknown Source:14)
                                                                                                    	at com.canopas.lib.showcase.component.ShowcaseContentKt$ShowcaseContent$6.invoke(Unknown Source:10)
                                                                                                    	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:235)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2838)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:3158)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose-aFTiNEg(Composer.kt:3706)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recompose-aFTiNEg$runtime_release(Composer.kt:3648)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:1002)
                                                                                                    	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1266)
                                                                                                    	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:142)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:620)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:591)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:39)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:108)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1506)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1517)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1085)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:971)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1491)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:243)
                                                                                                    	at android.os.Looper.loop(Looper.java:338)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8521)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1064)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@50dfe10, androidx.compose.ui.platform.MotionDurationScaleImpl@abe3d09, StandaloneCoroutine{Cancelling}@78eeb0e, AndroidUiDispatcher@e4c892f]
```
